# src/optees/utility/milp_utils.py
"""
Mixed-Integer Linear Programming (MILP) utilities.

Public API
----------
- solve_milp(problem, *, time_limit=None)
    Solve a MILP given a canonical problem dictionary.

Backends
--------
- OR-Tools CP-SAT (cp_model):
    Used when ALL variables are integer/binary AND all data (objective
    coefficients, matrix coefficients, RHS, bounds) are integer-like.
    This typically gives stronger performance on pure/MIP integer models.
- OR-Tools CBC (linear_solver.CBC):
    Fallback when any variable is continuous or when any coefficient is
    non-integer. Supports true mixed-integer models.

Canonical input (adapters must conform)
---------------------------------------
problem = {
  "sense": "min" | "max",
  "c": [c1, ..., cn],
  "A_ub": [[...], ...] | None,  # <= constraints
  "b_ub": [ ... ] | None,
  "A_eq": [[...], ...] | None,  # == constraints
  "b_eq": [ ... ] | None,
  "bounds": [(lb, ub), ...],    # optional; default (0, +inf) in CBC, (0, large) in CP-SAT
  "integrality": ["B"|"I"|None, ...],  # "B"=binary, "I"=general integer, None/"C"=continuous
  "var_names": ["x0","x1",...], # optional autogenerated names if missing
  "obj_offset": float,          # optional constant added to objective
  "time_limit": float,          # optional seconds
  "mip_gap": float              # optional relative gap, currently applied to CP-SAT
}

Return value
------------
(status, objective, x_dict, extras)
- status: "Optimal" | "Feasible" | "Infeasible" | "Unbounded" | "NotSolved"
- objective: float | None (set for Optimal and Feasible incumbents)
- x_dict: {var_name: value} | {} (values for Optimal and Feasible incumbents)
- extras: backend diagnostics (status codes, time, best bound, etc.)

Notes
-----
- time_limit (seconds): soft limit passed to the backend. CP-SAT stops
  at the limit and may return "Feasible" when it has an incumbent that is
  not yet proven optimal.
  CBC stops at the limit and returns the best status it has.
- CP-SAT requires integer-like data (we round-check with a small tolerance).
  When data is not integer-like, we fall back to CBC automatically.
"""

from __future__ import annotations
from typing import Any, Dict, List, Optional, Tuple

try:
    from ortools.sat.python import cp_model
    from ortools.linear_solver import pywraplp
    _ortools_import_error = None
except Exception as e:
    cp_model = None
    pywraplp = None
    _ortools_import_error = e

__all__ = ["solve_milp"]


def solve_milp(
    problem: Dict[str, Any], *, time_limit: Optional[float] = None
) -> Tuple[str, Optional[float], Dict[str, float], Dict[str, Any]]:
    """
    Solve a MILP using OR-Tools.

    The solver automatically chooses between:
    - CP-SAT: if all variables are integer/binary and all data are integer-like.
    - CBC:    otherwise (mixed variables and/or non-integer data).

    Parameters
    ----------
    problem : dict
        Canonical MILP problem dictionary (see module docstring).
    time_limit : float | None, optional
        Time limit in seconds; if None or <= 0, no explicit limit is set.

    Returns
    -------
    status : str
        "Optimal", "Feasible", "Infeasible", "Unbounded", or "NotSolved".
    objective : float | None
        Objective value if status == "Optimal" or "Feasible"; else None.
    x_dict : dict[str, float]
        Variable values if status == "Optimal" or "Feasible"; else {}.
    extras : dict[str, Any]
        Backend diagnostics (status codes, wall time, bound, nodes, etc.).

    Raises
    ------
    ValueError
        On malformed input (shape mismatch, unknown tokens, etc.).
    """
    if cp_model is None or pywraplp is None:
        return "NotSolved", None, {}, {
            "error": f"OR-Tools not available: {_ortools_import_error}",
            "backend": None,
        }

    P = _normalize(problem)
    effective_time_limit = (
        time_limit if time_limit is not None else _optional_positive_float(problem.get("time_limit"))
    )

    # If any continuous variable or any non-integer coefficient -> CBC
    if _needs_cbc(P):
        return _solve_mip_cbc_mixed(P, time_limit=effective_time_limit)

    # Otherwise CP-SAT (pure integer model with integer-like data)
    model, xs = _build_model(P)
    solver, status_code = _solve_model(
        model,
        time_limit=effective_time_limit,
        mip_gap=P.get("mip_gap"),
    )
    return _pack_result(solver, status_code, xs, P)


# ---------------------------------------------------------------------------
# CBC backend (mixed variables and/or non-integer data)
# ---------------------------------------------------------------------------

def _solve_mip_cbc_mixed(
    P: Dict[str, Any], time_limit: Optional[float] = None
) -> Tuple[str, Optional[float], Dict[str, float], Dict[str, Any]]:
    """
    Solve a (possibly mixed) MILP with OR-Tools CBC (linear_solver).

    Uses continuous variables for integrality=None and integer/binary for
    'I'/'B'. Supports <= and == constraints, objective in min/max.

    Parameters
    ----------
    P : dict
        Normalized canonical problem.
    time_limit : float | None
        Time limit in seconds (soft limit).

    Returns
    -------
    Same 4-tuple as `solve_milp`.
    """
    solver = pywraplp.Solver.CreateSolver("CBC")
    if solver is None:
        return "NotSolved", None, {}, {"error": "CBC solver not available"}

    if time_limit and time_limit > 0:
        solver.SetTimeLimit(int(time_limit * 1000))

    sense = P.get("sense", "min").lower()
    c = P["c"]
    bounds = P.get("bounds", [(0, None)] * len(c))
    integrality = P.get("integrality", [None] * len(c))
    names = P.get("var_names", [f"x{i}" for i in range(len(c))])

    # Variables
    xs: List[pywraplp.Variable] = []
    inf = solver.infinity()
    for i, (lb, ub) in enumerate(bounds):
        lbv = 0.0 if lb is None else float(lb)
        ubv = inf if ub is None else float(ub)
        integ = integrality[i]
        name = names[i]

        if integ in ("B", "I"):
            # Binary: ensure upper bound 1
            if integ == "B":
                ubv = min(ubv, 1.0)
            x = solver.IntVar(lbv, ubv, name)
        else:
            x = solver.NumVar(lbv, ubv, name)
        xs.append(x)

    # Equality constraints
    A_eq, b_eq = P.get("A_eq"), P.get("b_eq")
    if A_eq is not None and b_eq is not None:
        for row, rhs in zip(A_eq, b_eq):
            solver.Add(sum(float(a) * x for a, x in zip(row, xs)) == float(rhs))

    # <= constraints
    A_ub, b_ub = P.get("A_ub"), P.get("b_ub")
    if A_ub is not None and b_ub is not None:
        for row, rhs in zip(A_ub, b_ub):
            solver.Add(sum(float(a) * x for a, x in zip(row, xs)) <= float(rhs))

    # Objective
    expr = sum(float(ci) * x for ci, x in zip(c, xs))
    if sense == "min":
        solver.Minimize(expr)
    else:
        solver.Maximize(expr)

    res = solver.Solve()

    if res == pywraplp.Solver.OPTIMAL:
        status = "Optimal"
    elif res == pywraplp.Solver.FEASIBLE:
        status = "Feasible"
    elif res == pywraplp.Solver.INFEASIBLE:
        status = "Infeasible"
    elif res == pywraplp.Solver.UNBOUNDED:
        status = "Unbounded"
    else:
        status = "NotSolved"

    if status in {"Optimal", "Feasible"}:
        obj = solver.Objective().Value() + P.get("obj_offset", 0.0)
        xdict = {n: xs[i].solution_value() for i, n in enumerate(names)}
    else:
        obj, xdict = None, {}

    best_bound = _best_bound_cbc(solver)

    extras = {
        "backend": "cbc",
        "result_status": int(res),
        "wall_time_ms": solver.wall_time(),
        "nodes": _safe_callable_int(solver, "nodes"),
        "best_bound": best_bound,
        "relative_gap": _relative_gap(obj, best_bound),
        "mip_gap_requested": P.get("mip_gap"),
    }
    return status, obj, xdict, extras


# ---------------------------------------------------------------------------
# CP-SAT backend (all-integer variables + integer-like data)
# ---------------------------------------------------------------------------

def _normalize(problem: Dict[str, Any]) -> Dict[str, Any]:
    """
    Validate and normalize the canonical MILP dictionary.

    Ensures lengths match, normalizes 'integrality' tokens, sets defaults
    for missing sections, and carries an optional 'obj_offset'.

    Returns
    -------
    P : dict
        Normalized problem with keys:
        - sense, c, n, integrality, bounds, var_names,
          A_eq, b_eq, A_ub, b_ub, obj_offset
    """
    sense = (problem.get("sense", "min") or "min").lower()
    if sense not in ("min", "max"):
        raise ValueError("problem['sense'] must be 'min' or 'max'.")

    c = list(problem["c"])
    n = len(c)

    # integrality: accept "B", "I", None (or "C" treated as None)
    integ_in = problem.get("integrality", [None] * n)
    if len(integ_in) != n:
        raise ValueError("len(integrality) must match len(c).")
    integrality: List[Optional[str]] = []
    for t in integ_in:
        if t in ("B", "I", None):
            integrality.append(t)
        elif t == "C":
            integrality.append(None)
        else:
            raise ValueError(f"Unknown integrality token: {t!r}")

    bounds_in = problem.get("bounds")
    if bounds_in is None:
        bounds = [(0, None)] * n
    else:
        if len(bounds_in) != n:
            raise ValueError("len(bounds) must match len(c).")
        bounds = [(lb, ub) for (lb, ub) in bounds_in]

    names = problem.get("var_names") or [f"x{i}" for i in range(n)]
    if len(names) != n:
        raise ValueError("len(var_names) must match len(c).")

    A_eq, b_eq = problem.get("A_eq"), problem.get("b_eq")
    if (A_eq is None) ^ (b_eq is None):
        raise ValueError("A_eq and b_eq must be both present or both absent.")
    A_ub, b_ub = problem.get("A_ub"), problem.get("b_ub")
    if (A_ub is None) ^ (b_ub is None):
        raise ValueError("A_ub and b_ub must be both present or both absent.")

    return dict(
        sense=sense, c=c, n=n,
        integrality=integrality,
        bounds=bounds,
        var_names=names,
        A_eq=A_eq, b_eq=b_eq,
        A_ub=A_ub, b_ub=b_ub,
        obj_offset=float(problem.get("obj_offset", 0.0)),
        mip_gap=_optional_positive_float(problem.get("mip_gap")),
    )


def _as_int(x: float, name: str) -> int:
    """
    Convert a number to int if it is integer-like (within 1e-9 tolerance).

    Used by CP-SAT path to guarantee integral coefficients and bounds.
    """
    r = round(float(x))
    if abs(float(x) - r) > 1e-9:
        raise ValueError(f"{name} must be integer-like for CP-SAT, got {x!r}")
    return int(r)


def _build_model(P: Dict[str, Any]) -> Tuple[cp_model.CpModel, List[cp_model.IntVar]]:
    """
    Build a CP-SAT model for a pure-integer problem with integer-like data.

    Variables
    ---------
    - 'B' -> BoolVar in [0,1]
    - 'I' -> IntVar in [lb, ub], both integer-like (defaults lb=0 if None, ub=1e9 if None)

    Constraints
    -----------
    - A_eq x == b_eq
    - A_ub x <= b_ub
      (all coefficients and RHS must be integer-like)

    Objective
    ---------
    Minimize/Maximize sum(c_i * x_i), c_i integer-like.
    """
    m = cp_model.CpModel()

    xs: List[cp_model.IntVar] = []
    for i in range(P["n"]):
        kind = P["integrality"][i]
        name = P["var_names"][i]
        lb, ub = P["bounds"][i]

        if kind == "B":
            xs.append(m.NewBoolVar(name))
            continue

        lo = _as_int(0 if lb is None else lb, f"lb[{i}]")
        hi = 10**9 if ub is None else _as_int(ub, f"ub[{i}]")
        if lo > hi:
            raise ValueError(f"Invalid bounds for {name}: [{lo}, {hi}]")
        xs.append(m.NewIntVar(lo, hi, name))

    # Equality constraints
    if P["A_eq"] is not None:
        if len(P["A_eq"]) != len(P["b_eq"]):
            raise ValueError("len(A_eq) must match len(b_eq).")
        for r, (row, rhs) in enumerate(zip(P["A_eq"], P["b_eq"])):
            if len(row) != P["n"]:
                raise ValueError("A_eq row length must match n.")
            coeffs = [_as_int(aij, f"A_eq[{r},{j}]") for j, aij in enumerate(row)]
            m.Add(sum(coeffs[j] * xs[j] for j in range(P["n"])) == _as_int(rhs, f"b_eq[{r}]"))

    # <= constraints
    if P["A_ub"] is not None:
        if len(P["A_ub"]) != len(P["b_ub"]):
            raise ValueError("len(A_ub) must match len(b_ub).")
        for r, (row, rhs) in enumerate(zip(P["A_ub"], P["b_ub"])):
            if len(row) != P["n"]:
                raise ValueError("A_ub row length must match n.")
            coeffs = [_as_int(aij, f"A_ub[{r},{j}]") for j, aij in enumerate(row)]
            m.Add(sum(coeffs[j] * xs[j] for j in range(P["n"])) <= _as_int(rhs, f"b_ub[{r}]"))

    # Objective
    coefs = [_as_int(ci, f"c[{i}]") for i, ci in enumerate(P["c"])]
    lin = sum(coefs[i] * xs[i] for i in range(P["n"]))
    m.Minimize(lin) if P["sense"] == "min" else m.Maximize(lin)

    return m, xs


def _solve_model(
    model: cp_model.CpModel,
    *,
    time_limit: Optional[float],
    mip_gap: Optional[float],
) -> Tuple[cp_model.CpSolver, int]:
    """
    Solve the CP-SAT model and return (solver, status_code).

    Parameters
    ----------
    model : cp_model.CpModel
        The built CP-SAT model.
    time_limit : float | None
        Time limit in seconds.

    Returns
    -------
    solver : cp_model.CpSolver
        The solver instance, populated with the solution if any.
    status_code : int
        One of cp_model.OPTIMAL, INFEASIBLE, FEASIBLE, MODEL_INVALID, UNKNOWN.
    """
    solver = cp_model.CpSolver()
    if time_limit and time_limit > 0:
        solver.parameters.max_time_in_seconds = float(time_limit)
    if mip_gap and mip_gap > 0:
        solver.parameters.relative_gap_limit = float(mip_gap)
    # Multi-thread by default; adjust if deterministic runs are needed
    solver.parameters.num_search_workers = 8
    status_code = solver.Solve(model)
    return solver, status_code


def _pack_result(
    solver: cp_model.CpSolver, status_code: int, xs: List[cp_model.IntVar], P: Dict[str, Any]
) -> Tuple[str, Optional[float], Dict[str, float], Dict[str, Any]]:
    """
    Map CP-SAT results to the public (status, objective, x_dict, extras) tuple.

    Notes
    -----
    - We report FEASIBLE separately because MILP solvers often have a useful
      incumbent before they prove optimality.
    """
    if status_code == cp_model.OPTIMAL:
        status = "Optimal"
    elif status_code == cp_model.FEASIBLE:
        status = "Feasible"
    elif status_code == cp_model.INFEASIBLE:
        status = "Infeasible"
    else:
        status = "NotSolved"

    x_dict: Dict[str, float] = {}
    obj: Optional[float] = None
    if status in {"Optimal", "Feasible"}:
        for i, v in enumerate(xs):
            x_dict[P["var_names"][i]] = float(solver.Value(v))
        obj = float(solver.ObjectiveValue() + P["obj_offset"])

    # BestObjectiveBound may not exist in older OR-Tools; guard access.
    best_bound = None
    if hasattr(solver, "BestObjectiveBound"):
        try:
            best_bound = solver.BestObjectiveBound()
        except Exception:
            best_bound = None

    extras: Dict[str, Any] = {
        "backend": "cp-sat",
        "status_code": int(status_code),
        "status_str": solver.StatusName(status_code),
        "best_bound": best_bound,
        "relative_gap": _relative_gap(obj, best_bound),
        "wall_time": solver.WallTime(),
        "conflicts": solver.NumConflicts(),
        "branches": solver.NumBranches(),
        "mip_gap_requested": P.get("mip_gap"),
    }
    return status, obj, x_dict, extras


def _optional_positive_float(value: Any) -> Optional[float]:
    if value is None:
        return None
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    return parsed if parsed > 0 else None


def _relative_gap(obj: Optional[float], bound: Optional[float]) -> Optional[float]:
    """Return |obj-bound| / max(1, |obj|) for incumbent diagnostics."""
    if obj is None or bound is None:
        return None
    try:
        return abs(float(obj) - float(bound)) / max(1.0, abs(float(obj)))
    except (TypeError, ValueError, OverflowError):
        return None


def _safe_callable_int(obj: Any, name: str) -> Optional[int]:
    attr = getattr(obj, name, None)
    if attr is None:
        return None
    try:
        value = attr() if callable(attr) else attr
        return int(value)
    except Exception:
        return None


def _best_bound_cbc(solver: Any) -> Optional[float]:
    objective = getattr(solver, "Objective", lambda: None)()
    if objective is None:
        return None
    for attr_name in ("BestBound", "best_bound"):
        attr = getattr(objective, attr_name, None)
        if attr is None:
            continue
        try:
            value = attr() if callable(attr) else attr
            return float(value)
        except Exception:
            continue
    return None


# ---------------------------------------------------------------------------
# Routing logic: decide CP-SAT vs CBC
# ---------------------------------------------------------------------------

def _is_int_like(x: float, tol: float = 1e-9) -> bool:
    """Return True if x is within `tol` of an integer."""
    xf = float(x)
    return abs(xf - round(xf)) <= tol


def _all_data_integer(P: Dict[str, Any]) -> bool:
    """Check that objective, bounds, matrices, RHS are all integer-like."""
    # Objective
    if not all(_is_int_like(ci) for ci in P["c"]):
        return False
    # Bounds
    for lb, ub in P["bounds"]:
        if lb is not None and not _is_int_like(lb):
            return False
        if ub is not None and not _is_int_like(ub):
            return False
    # A_eq/b_eq
    if P["A_eq"] is not None:
        if not all(all(_is_int_like(a) for a in row) for row in P["A_eq"]):
            return False
        if not all(_is_int_like(b) for b in P["b_eq"]):
            return False
    # A_ub/b_ub
    if P["A_ub"] is not None:
        if not all(all(_is_int_like(a) for a in row) for row in P["A_ub"]):
            return False
        if not all(_is_int_like(b) for b in P["b_ub"]):
            return False
    return True


def _needs_cbc(P: Dict[str, Any]) -> bool:
    """
    Decide if we must use CBC (mixed or non-integer data) instead of CP-SAT.

    Returns
    -------
    True if:
      - any variable is continuous (integrality token is neither "B" nor "I"), or
      - any coefficient/bound/RHS/objective is not integer-like.
    """
    has_continuous = any(t not in ("B", "I") for t in P["integrality"])
    if has_continuous:
        return True
    if not _all_data_integer(P):
        return True
    return False
