"""Stable public identifiers for executable Optees capabilities."""

LP_CAPABILITY_ID = "lp.continuous"
QP_CAPABILITY_ID = "qp.continuous"
MILP_CAPABILITY_ID = "milp.linear"
SCENARIO_MIN_MAX_LOSS_CAPABILITY_ID = "scenario.linear.min_max_loss"
SCENARIO_MAX_MIN_REWARD_CAPABILITY_ID = "scenario.linear.max_min_reward"

KNAPSACK_ZERO_ONE_CAPABILITY_ID = "knapsack.zero_one"
KNAPSACK_BOUNDED_CAPABILITY_ID = "knapsack.bounded"
KNAPSACK_UNBOUNDED_CAPABILITY_ID = "knapsack.unbounded"
KNAPSACK_FRACTIONAL_CAPABILITY_ID = "knapsack.fractional"
KNAPSACK_MULTI_DIMENSIONAL_CAPABILITY_ID = "knapsack.multi_dimensional"

DIJKSTRA_CAPABILITY_ID = "graph.shortest_path.dijkstra"
NLP_CAPABILITY_ID = "nlp.continuous_local"
REGRESSION_CAPABILITY_ID = "ml.regression.linear"
CLASSIFICATION_CAPABILITY_ID = "ml.classification.binary_logistic"
FORECASTING_CAPABILITY_ID = "ml.forecasting.univariate"
PACKING_CAPABILITY_ID = "packing.single_container_3d"

PUBLIC_CAPABILITY_IDS = (
    LP_CAPABILITY_ID,
    QP_CAPABILITY_ID,
    MILP_CAPABILITY_ID,
    SCENARIO_MIN_MAX_LOSS_CAPABILITY_ID,
    SCENARIO_MAX_MIN_REWARD_CAPABILITY_ID,
    KNAPSACK_ZERO_ONE_CAPABILITY_ID,
    KNAPSACK_BOUNDED_CAPABILITY_ID,
    KNAPSACK_UNBOUNDED_CAPABILITY_ID,
    KNAPSACK_FRACTIONAL_CAPABILITY_ID,
    KNAPSACK_MULTI_DIMENSIONAL_CAPABILITY_ID,
    DIJKSTRA_CAPABILITY_ID,
    NLP_CAPABILITY_ID,
    REGRESSION_CAPABILITY_ID,
    CLASSIFICATION_CAPABILITY_ID,
    FORECASTING_CAPABILITY_ID,
    PACKING_CAPABILITY_ID,
)
